version: '3.8'

services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - laravel_network

  app:
    build: .
    container_name: laravel-app
    ports:
      - '${APP_PORT:-8080}:80'
    volumes:
      - .:/var/www/app
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /var/www/app
    networks:
      - laravel_network

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: laravel-pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '8081:80'
    networks:
      - laravel_network

volumes:
  sail-mysql:
    driver: local

networks:
  laravel_network:
    driver: bridge
